spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rooms_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:  
      ddl-auto: update
    show-sql: true    
